### ISSUE TITLE
admin: methods to select replicas for log stream

### ISSUE THREAD

**Issue by ijsong** [kakao/varlog#393]
When the admin makes a log stream, it can select replicas automatically if a client does not send the log stream's topology. The admin provides the interface `ReplicaSelector` to support various methods of choosing replicas.

```go
// ReplicaSelector selects storage nodes and volumes to store data for replicas of a new log stream.
// This method returns a slice of `varlogpb.ReplicaDescriptor`, and its length should be equal to the
// replication factor.
type ReplicaSelector interface {
	Select(ctx context.Context) ([]*varlogpb.ReplicaDescriptor, error)
}
```

Currently, the admin provides `balancedReplicaSelector`, which implements `ReplicaSelector`; however, it does not work well because it is unnecessarily too complex. Therefore we have to revisit it.

Goals:

- Pluggable replica selection algorithm
- Override mechanism to replace global algorithm with a topic-specific algorithm
- Call-specific algorithm

Implementation plan:

- [x] Add a method `Name` to the `ReplicaSelector` interface, which returns a unique name of each replica selector. The name can define the replica selector that the admin server uses. #394 
- [x] Add a new replica selector, `random`. When there are many storage nodes, replicas of a log stream can be chosen randomly. #395 
- [x] Refactor or rework existing replica selector, `balancedReplicaSelector`. It will deploy replicas across storage nodes to balance the number of replicas per storage node and the number of primary replicas per storage node. #396 
- [x] Add a flag to specify the global default replica selector. #402 
- [ ] Add a property to the topic that specifies the default replica selector.
- [ ] Add a call option to the AddLogStream, which specifies a replica selector for the call.
