### ISSUE TITLE
Performance Analysis and Improvement of LogStream Primary-Backup Replication

### ISSUE THREAD

**Issue by ijsong** [kakao/varlog#795]
# Background
This issue aims to analyze and improve the performance of LogStream's Primary-Backup Replication. First, we need to define the metrics that accurately reflect replication performance. Currently, there are metrics such as `sn.replicate.logs`, `sn.replicate.bytes`, and `sn.replicate.duration`. However, these metrics only provide average values for replication throughput and response time. These metrics need to be redefined to conduct a detailed analysis using percentiles.

# Problem: Current Structure
The replication gRPC operates as follows: the Primary Replica invokes the Backup Replica's Replicate RPC. In this setup, the Backup Replica acts as the gRPC server, while the Primary Replica acts as the client. The Primary Replica sends batches of LogEntry to the Backup Replica using the Replicate RPC.

1. **Primary Replica**: Sends batches of LogEntry via Replicate RPC.
2. **Backup Replica**:
    - **Receiver Goroutine**: This goroutine acts as the gRPC Receiver, receiving ReplicateRequest through Replicate RPC and placing it into a queue as ReplicationRequestTask.
    - **Replicator Goroutine**: This goroutine takes ReplicationRequestTask from the queue and uses it to call LogStreamExecutor's Replicate method.

The Receiver goroutine defines ReplicateRequest once and uses it continuously. However, the gRPC Unmarshal code repeatedly generates slices for some fields, such as LLSN and Data. Although the protobuf message ReplicateRequest is reused, the slices included are not, causing degraded performance.

https://github.com/kakao/varlog/blob/fd1b084a9a8a0ae4daa1511f34d27eba821e3ed6/proto/snpb/replicator.pb.go#L69-L76
https://github.com/kakao/varlog/blob/fd1b084a9a8a0ae4daa1511f34d27eba821e3ed6/internal/storagenode/replication_server.go#L109-L133

# Proposed Optimizations
The following ideas are proposed to optimize the replication process:

1. **Use `sync.Pool` for ReplicateRequest**: Utilize `sync.Pool` to reuse ReplicateRequest structures.
2. **Reuse Slices**: Extend the Reset method generated in gRPC to reuse slice-type fields - `LLSN` and `Data` - of the ReplicateRequest struct.

The proposed optimization aims to reuse these fields to enhance Unmarshal's performance. The longer the batch size, the more allocations for the slices there are, so reusing them seems promising. Furthermore, append entries into the slices cause copy overhead whenever the underlying heaps enlarge. This optimization may greatly reduce this overhead.

To reuse the slice in the protobuf message, the following code can be used:
```go
func (m *ReplicateRequest) ResetReuse() {
	s := m.LLSN[:0]
	m.Reset()
	m.LLSN = s
}
```

In the case of `snpb.(ReplicateRequest).Data`, the outer slice can be reused using the above code. However, we should change the unmarshalling code generated by gRPC to reuse the inner slice.

# Plan

- [x] Define new metrics that include percentiles for detailed analysis. (#806)
- [x] Utilize `sync.Pool` to efficiently reuse ReplicateRequest structures. (#808)
- [x] Implement reuse of LLSN and Data fields in ReplicateRequest to reduce overhead. (#808)
